### ISSUE TITLE
service crash with android_new toolchain

### ISSUE THREAD

**Issue by oceanpix** [tshirtman/kivy_service_osc#1]
Hi! 
On my device, this application crash as soon as it's started. Funny thing is that it happen just when the build is compiled through the "android_new" toolchain rather than the old "android". 

I can't really say if the issue comes from the code or the toolchain, but commenting the line #48 (autostart of the service) the app open correctly. Then if I manually hit the button to "start service" appear crash pop-up: "Unfortunately, Kivy service OSC demo has stopped"

Should be indicated some other modules in buildozer when building with the android_new toolchain?
Thanks!

**Comment by khertan** [comment]
+1

01-27 21:59:34.026  1585   986 I ActivityManager: Process org.kivy.oscservice:pythonservice (pid 27697)(adj 2) has died(32,397)
01-27 21:59:41.826  1585  1607 I ActivityManager: Start proc 27982:org.kivy.oscservice:pythonservice/u0a808 for service org.kivy.oscservice/org.kivy.android.PythonService
01-27 21:59:41.836 27982 27982 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.kivy.oscservice:pythonservice 
01-27 21:59:41.936 27982 27995 W linker  : /data/app/org.kivy.oscservice-2/lib/arm/libpython2.7.so: is missing DT_SONAME will use basename as a replacement: "libpython2.7.so"
01-27 21:59:41.946 27982 27995 W linker  : /data/data/org.kivy.oscservice/files/app/lib/python2.7/lib-dynload/_io.so: is missing DT_SONAME will use basename as a replacement: "_io.so"
01-27 21:59:41.956 27982 27995 W linker  : /data/data/org.kivy.oscservice/files/app/lib/python2.7/lib-dynload/unicodedata.so: is missing DT_SONAME will use basename as a replacement: "unicodedata.so"
01-27 21:59:41.956 27982 27995 W linker  : /data/data/org.kivy.oscservice/files/app/lib/python2.7/lib-dynload/_ctypes.so: is missing DT_SONAME will use basename as a replacement: "_ctypes.so"
01-27 21:59:42.296   390   390 F DEBUG   : pid: 27982, tid: 27995, name: Thread-58479  >>> org.kivy.oscservice:pythonservice <<<
01-27 21:59:42.846  1585  2170 I ActivityManager: Process org.kivy.oscservice:pythonservice (pid 27982)(adj 2) has died(52,388)

**Comment by mvukadinoff** [comment]
The latest buildozer now has the new toolset as target by default

> buildozer android_new debug                                                                     
> # Check configuration tokens
> # ERROR: The target android_new is now android
> 

And the service fails for me as well. This becomes a critical bug I think:
```

I/ActivityManager(  917): Start proc com.itgix.ziose:pythonservice for service com.itgix.ziose/org.kivy.android.PythonService: pid=23439 uid=10105 gids={50105, 9997, 1028, 1015, 3003} abi=armeabi-v7a
I/python  (23412): [INFO   ] [Activity    ] Start service
V/PythonUtil(23439): Loaded everything!
F/art     (23439): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received null jstring
F/art     (23439): art/runtime/check_jni.cc:65]     in call to GetStringUTFChars
F/art     (23439): art/runtime/check_jni.cc:65]     from void org.kivy.android.PythonService.nativeStart(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)

```

**Comment by jtoledo1974** [comment]
Same here with the latest toolchain. Hasn't anyone found a workaround yet?

**Comment by mvukadinoff** [comment]
The only workaround we apply is to use the old chain like:
 buildozer android_old debug

**Comment by jtoledo1974** [comment]
Using android_old as well. I do believe this should be a critical bug as the new way is the default.

**Comment by kennedyshead** [comment]
This really needs fixing!

**Comment by tshirtman** [comment]
woah, sorry people, i didn't even see this report earlier, looking into it, updating to use the new service api seems the way forward.

**Comment by monojk** [comment]
Any progress on this issue? I have the same problem "Kivy service OSC demo has stopped"
I cannot use android_old : 
Using "buildozer android_old debug deploy run" I get an error: "Failed to read python-for-android setup.py at /home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/python-for-android/setup.py"

**Comment by tshirtman** [comment]
Can you try again after the latest push? it works well for me with latest p4a and a recent buildozer.

**Comment by monojk** [comment]
Thanks. Yet I have a problem with my settings probably in buildozer.spec that seem to be contradictory to:
````
SERVICE_NAME = u'{packagename}.Service{servicename}'.format(
    packagename=u'org.kivy.oscservice',
    servicename=u'Pong'
)
````
buildozer.spec:
````
# (str) Title of your application
title = Kivy service OSC demo

# (str) Package name
package.name = oscservice

# (str) Package domain (needed for android/ios packaging)
package.domain = org.kivy
````

**Comment by tshirtman** [comment]
Sorry, didn't get time to investigate, but this classname is correct (dots replaced by slashes), and the code works as-is for me, are you sure you cleaned everything and had a working build?

**Comment by monojk** [comment]
I removed the .buildozer dir used your buildozer spec, but now when launching the app I get this error, previously I initially got the apps screen: 

 


03-12 17:42:58.682  8151  8182 I python  :  Traceback (most recent call last):
03-12 17:42:58.682  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/app/main.py", line 110, in <module>
03-12 17:42:58.683  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/app.py", line 855, in run
03-12 17:42:58.684  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/base.py", line 502, in runTouchApp
03-12 17:42:58.685  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/core/window/window_sdl2.py", line 724, in mainloop
03-12 17:42:58.686  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/core/window/window_sdl2.py", line 459, in _mainloop
03-12 17:42:58.687  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/base.py", line 337, in idle
03-12 17:42:58.688  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/clock.py", line 581, in tick
03-12 17:42:58.689  8151  8182 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
03-12 17:42:58.690  8151  8182 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
03-12 17:42:58.691  8151  8182 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
03-12 17:42:58.692  8151  8182 I python  :    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
03-12 17:42:58.693  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/kivy/base.py", line 208, in remove_android_splash
03-12 17:42:58.693  8151  8182 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/platform/build/build/python-installs/oscservice/android/__init__.py", line 8, in <module>
03-12 17:42:58.694  8151  8182 I python  :    File "android/_android.pyx", line 178, in init android._android
03-12 17:42:58.695  8151  8182 I python  :  AttributeError: 'str' object has no attribute 'decode'
03-12 17:42:58.696  8151  8182 I python  : Python for android ended.

 


Any advise?

Gesendet: Dienstag, 12. März 2019 um 15:27 Uhr
Von: "Gabriel Pettier" <notifications@github.com>
An: tshirtman/kivy_service_osc <kivy_service_osc@noreply.github.com>
Cc: monojk <jkeinert@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [tshirtman/kivy_service_osc] service crash with android_new toolchain (#1)


Sorry, didn't get time to investigate, but this classname is correct (dots replaced by slashes), and the code works as-is for me, are you sure you cleaned everything and had a working build?

**Comment by brvier** [comment]
Are you using Python3.
For me this is fixed with py2

**Comment by mehdializade** [comment]
It works to get the debug file, but when I use the `buildozer -v android release`
 command, I get the following message. Where does the problem come from?
 ```
# 
# ERROR: Trying to release a package that starts with org.kivy
# 
# The package.domain org.kivy is reserved for the Kivy official
# applications. Please use your own domain.
# 
# If you are a Kivy developer, add an export in your shell
# export BUILDOZER_ALLOW_KIVY_ORG_DOMAIN=1
# 

```
