### ISSUE TITLE
ImportError: cannot import name 'osc' from 'kivy.lib'

### ISSUE THREAD

**Issue by monojk** [tshirtman/kivy_service_osc#2]
Hi, I'm new with kivy and wanted to run the kivy_service_osc example.
Yet, I get a "ImportError: No module named android". I have tried several things but always got this error and the kivy window does not appear.
my buildozer.spec has:
title = Kivy service OSC demo
package.name = serviceexample
package.domain = org.test
requirements = kivy
android.permissions = INTERNET
android.sdk = 20
android.ndk = 13b

I set NDK 13b because 9b isn't available anymore to download from Google.

I have attached the buildozer android logcat log from the respective process 3930

I don't know whether this is the right place to report my issue but didn't find another place.

**Comment by monojk** [comment]
when I add android to the requirements in buildozer.spec I get an error about unable to call a str.
commenting the line "platform = platform()" fixes it but there is still a problem as it dies:

F/libc    ( 5745): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 5759 (Thread-5044)
I/DEBUG   (  224): pid: 5745, tid: 5759, name: Thread-5044  >>> org.kivy.oscservice:pythonservice <<<
I/DEBUG   (  224): !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 5745
D/CrashAnrDetector(12262): pid: 5745, tid: 5759, name: Thread-5044  >>> org.kivy.oscservice:pythonservice <<<
I/ActivityManager(12262): Process org.kivy.oscservice:pythonservice (pid 5745) (adj 2) has died.

**Comment by monojk** [comment]
I have an update on the problem:
02-16 12:39:59.408 30487 30586 I python  :  Traceback (most recent call last):
02-16 12:39:59.409 30487 30586 I python  :    File "/home/joachim/PycharmProjects/kivy_service_osc/.buildozer/android/app/main.py", line 7, in <module>
02-16 12:39:59.410 30487 30586 I python  :  ImportError: **cannot import name 'osc' from 'kivy.lib'** (/data/user/0/org.kivy.oscservice/files/app/_python_bundle/site-packages/kivy/lib/__init__.pyc)

This is the start of the main.py:
`__version__ = '0.1'

# https://github.com/tshirtman/kivy_service_osc

from kivy.app import App
from kivy.lang import Builder
from kivy.lib import osc
from kivy.clock import Clock
from kivy.utils import platform
#platform = platform()
`

**Comment by tshirtman** [comment]
This example is outdated, as the osc lib has been removed from kivy, and replaced by kivy/oscpy, please have a look at it, porting to it should be easy. compared to the osc module we shipped before, oscpy is faster, is well tested (99% coverage), and supports python3.

**Comment by monojk** [comment]
Can you point me to the API doc please?
I cannot find oscpy in https://kivy.org/doc/stable/search.html?q=oscpy nor https://kivy.org/doc/master/search.html?q=oscpy
 

Gesendet: Samstag, 16. Februar 2019 um 23:46 Uhr
Von: "Gabriel Pettier" <notifications@github.com>
An: tshirtman/kivy_service_osc <kivy_service_osc@noreply.github.com>
Cc: monojk <jkeinert@web.de>, Author <author@noreply.github.com>
Betreff: Re: [tshirtman/kivy_service_osc] ImportError: cannot import name 'osc' from 'kivy.lib' (#2)


This example is outdated, as the osc lib has been removed from kivy, and replaced by kivy/oscpy, please have a look at it, porting to it should be easy. compared to the osc module we shipped before, oscpy is faster, is well tested (99% coverage), and supports python3.

**Comment by monojk** [comment]
Can you point me to the API doc please? 
I cannot find oscpy in https://kivy.org/doc/stable/search.html?q=oscpy nor https://kivy.org/doc/master/search.html?q=oscpy
